# Generated by Django 6.0.2 on 2026-02-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_myappointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myappointment',
            old_name='docter',
            new_name='doctor',
        ),
    ]
