# Generated by Django 6.0.2 on 2026-02-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_rename_docter_myappointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myappointment',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
